
services:
  backend:
    
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    ports:
      - "5000:5000"
    
    volumes:
      - ./backend:/app
     
      - /app/node_modules
    
    environment:
      NODE_ENV: development 
      MONGODB_URI: "mongodb+srv://jaimericardo:jaime.321Monitoreo@cluster0.scefps7.mongodb.net/monitoreo"
      restart: always
      
  frontend:
   
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    ports:
      - "5173:80"
   
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
    depends_on:
      - backend
   
    environment:
      
      REACT_APP_API_URL: http://backend:5000
      